### ISSUE TITLE
It seems some buffer are still "dirty"

### ISSUE THREAD

**Issue by DomDumont** [ClementRivaille/godot-simple-sampler#2]
Hi,
Thanks a lot for your sampler. I got one little problem with it : When I play only one note via the multisampler ( like this $AudioStreamPlayer/Multisampler.play_note("C") for example ) I got this note playing forever at a very slow rate like if a buffer was not reset. Maybe I am doing something wrong

**Comment by DomDumont** [comment]
oh I found, the problem was the loop flag when I imported the sound files; sorry

**Comment by ClementRivaille** [comment]
Hi. Glad you could find the solution. The loop flag being activated by default also gets me a lot of time! There's also a similar issue with some .wav files, which even without the flag will loop on a certain sequence. For those cases I recommend using the _sustain_ and _release_  parameters, which stop the sounds at a precise time.

**Comment by DomDumont** [comment]
I still have some strange crashes ( maybe due to godot html5 export ) but if you are curious about my stupid experiment https://domdumont.itch.io/musicexperiment-1
